name = "oakauth-api"
main = "src/index.ts"
compatibility_date = "2025-12-20"

routes = [
  { pattern = "api.oakauth.com/*", zone_name = "oakauth.com" }
]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "oakauth-db"
database_id = "51220a87-8e93-47e9-8b1c-bddcb9585309"
migrations_dir = "migrations"
